# -*- coding: utf-8 -*-
"""Data Science Project 2 - Febriarini Rismawati

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18eQyDgRPiwjT75Ie-KOwUpD-0SIGSASl
"""

#!python3
#!Author:Febriarini Rismawati

!pip install gspread==5.3.2
import gspread
from google.oauth2.service_account import Credentials

gspread.__version__

import pandas as pd
import numpy as np

import math

"""#Answering Questions"""

scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"]

credentials = Credentials.from_service_account_file(
    "/content/sample_data/ds13-febriarini-rismawati-4fd8bc4324e1.json",
    scopes=scopes)

gc = gspread.authorize(credentials)

file = gc.open("Raw Parkiran PT. SUMO UTOMO")

name_sheet = ['Jan-2021','Feb-2021','Mar-2021','Apr-2021','Mei-2021','Jun-2021',
              'Jul-2021','Agu-2021','Sep-2021','Okt-2021','Nov-2021','Des-2021']

data = pd.DataFrame(columns=['Gate', 'Vehicle', 'Entry', 'Exit'])

for i in name_sheet:
  sheet = file.worksheet(i)
  df = pd.DataFrame(sheet.get_all_records())
  data = data.append(df)


data['Entry'] = pd.to_datetime(data['Entry'])
data['Exit'] = pd.to_datetime(data['Exit'])
data['Month'] = data['Entry'].dt.month_name()

"""##1. Monthly and Overall Error Transactions Percentage"""

data['Validasi'] = data['Entry'] < data['Exit']
report_1 = data.groupby(['Month','Validasi']).agg({'Entry':'count'}).unstack().reset_index()
report_1.columns = ['Month','FALSE','TRUE']
report_1['PERCENTAGE'] = (report_1['FALSE']/(report_1['FALSE']+report_1['TRUE']))*100
report_1.to_excel('Report_1.xlsx', index=False)
report_1

"""##2. Monthly Transaction Income"""

da = data[data['Validasi'] == True].reset_index()

def get_hours(end,start):
  td = (end-start)
  minutes = td.total_seconds()/60
  hours = minutes/60
  days = hours/24
  
  return math.ceil(hours)

for index, row in da.iterrows():
  da.loc[index,'Duration'] = get_hours(row['Exit'], row['Entry'])

da.loc[da['Vehicle'] == 'Car', 'Price'] = da['Duration']*3000
da.loc[da['Vehicle'] == 'Motorcycle', 'Price'] = da['Duration']*2000

report_2 = da.groupby(['Month']).agg({'Price':'sum'}).reset_index()
report_2.to_excel('Report_2.xlsx', index=False)
report_2

"""##3. Vehicle-Based Monthly Income"""

da = data[data['Validasi'] == True].reset_index()

def get_hours(end,start):
  td = (end-start)
  minutes = td.total_seconds()/60
  hours = minutes/60
  days = hours/24
  
  return math.ceil(hours)

for index, row in da.iterrows():
  da.loc[index,'Duration'] = get_hours(row['Exit'], row['Entry'])

da.loc[da['Vehicle'] == 'Car', 'Price'] = da['Duration']*3000
da.loc[da['Vehicle'] == 'Motorcycle', 'Price'] = da['Duration']*2000

report_2 = da.groupby(['Vehicle']).agg({'Price':'sum'}).reset_index()
report_2.to_excel('Report_2.xlsx', index=False)
report_2